from __future__ import annotations

from datetime import datetime
from typing import Protocol

from .models import *


class CancellationSignal(Protocol):
    def is_cancelled(self) -> bool: ...


class ModelCatalogPort(Protocol):
    def register_provider(self, request): ...
    def register_model(self, request): ...
    def publish_profile(self, request): ...
    def publish_pricing(self, request): ...
    def change_model_status(self, request): ...
    def get_model(self, query): ...
    def list_models(self, query): ...
    def record_selection(self, selection: ModelSelection, snapshot: ApprovedModelRequirementsSnapshot) -> ModelSelection: ...
    def inspect_selection(self, query): ...
    def load_snapshot(self, reference: ApprovedModelRequirementsRef, context: ModelCatalogOperationContext) -> ApprovedModelRequirementsSnapshot: ...


class ModelResolver(Protocol):
    def resolve(self, request: ModelResolutionRequest) -> ModelResolutionOutcome: ...
    def resolve_fallback(self, request: ResolveFallback) -> ModelResolutionOutcome: ...


class ProviderPort(Protocol):
    def generate(self, request: ProviderInvocationRequest) -> ProviderOutcome: ...
    def open_stream(self, request: ProviderInvocationRequest) -> ProviderStream: ...
    def read_stream(self, request: ReadProviderStream) -> list[ProviderStreamEvent]: ...
    def cancel(self, request: CancelProviderInvocation) -> CancelProviderResult: ...
    def await_terminal(self, request: AwaitProviderTerminal) -> ProviderTerminalSnapshot: ...
    def inspect(self, query: AuthorizedProviderInvocationQuery): ...


ProviderInvocationPort = ProviderPort


class CatalogClock(Protocol):
    def now(self) -> datetime: ...


__all__ = [name for name in globals() if not name.startswith("_")]
