from __future__ import annotations

from datetime import datetime
from typing import Iterable, Mapping, Protocol

from .models import ProviderCatalogContext, ProviderModelRecord, RefreshReceipt


class ProviderCatalogRepository(Protocol):
    def credential(self, context: ProviderCatalogContext, provider: str) -> Mapping[str, object] | None: ...
    def replace(self, context: ProviderCatalogContext, provider: str, records: list[ProviderModelRecord], refreshed_at: datetime) -> None: ...
    def list(self, context: ProviderCatalogContext, provider: str, favorites_only: bool = False) -> list[ProviderModelRecord]: ...
    def set_favorite(self, context: ProviderCatalogContext, provider: str, model_id: str, favorite: bool) -> ProviderModelRecord: ...
    def add_custom(self, context: ProviderCatalogContext, provider: str, record: ProviderModelRecord) -> ProviderModelRecord: ...
    def remove_custom(self, context: ProviderCatalogContext, provider: str, model_id: str) -> None: ...


class ProviderCatalogUpstream(Protocol):
    # Declared here rather than left to each client's default, so the service
    # needs no per-provider branch to decide whether the kwarg is accepted.
    def fetch(self, api_key: str, *, base_url: str = "") -> list[dict[str, object]]: ...


class ProviderStreamTransport(Protocol):
    """Worker-side provider transport; credentials never cross this port."""
    def stream(self, request: Mapping[str, object]) -> Iterable[object]: ...


class ProviderModelCatalogPort(Protocol):
    def refresh(self, context: ProviderCatalogContext, provider: str) -> RefreshReceipt: ...
    def list(self, context: ProviderCatalogContext, provider: str, favorites_only: bool = False) -> list[ProviderModelRecord]: ...
    def favorite(self, context: ProviderCatalogContext, provider: str, model_id: str, favorite: bool) -> ProviderModelRecord: ...
    def add_custom(self, context: ProviderCatalogContext, provider: str, model_id: str, display_name: str | None = None) -> ProviderModelRecord: ...
    def remove_custom(self, context: ProviderCatalogContext, provider: str, model_id: str) -> None: ...
