from __future__ import annotations

from datetime import datetime
from typing import Protocol

from .models import (
    AuthorizedTerminalQuery,
    CancelTerminalCommand,
    CancelTerminalResult,
    CloseTerminalResult,
    CloseTerminalSession,
    CommandFailed,
    CommandExited,
    ExecuteTerminalCommand,
    InputWriteResult,
    ProcessExitState,
    ProcessTreeSnapshot,
    SignalReceipt,
    StreamDisposition,
    StreamResult,
    StreamTerminalOutput,
    TerminalCommandAccepted,
    TerminalCommandOutcome,
    TerminalError,
    TerminalOperationContext,
    TerminalSessionSnapshot,
    TerminationResult,
    WriteTerminalInput,
    CreateTerminalSession,
)


class TerminalOutputSink(Protocol):
    def emit(self, chunk) -> StreamDisposition: ...
    def close(self, outcome: TerminalCommandOutcome | None) -> None: ...


class ProcessSupervisor(Protocol):
    def signal(self, command_id: str, signal: str) -> SignalReceipt: ...
    def await_exit(self, command_id: str, deadline: datetime) -> ProcessExitState: ...
    def terminate_tree(self, session_id: str, deadline: datetime) -> TerminationResult: ...
    def reconcile(self, session_id: str, context: TerminalOperationContext) -> ProcessTreeSnapshot: ...


class TerminalAdapter(Protocol):
    def create_session(self, request: CreateTerminalSession) -> object | TerminalError: ...
    def execute(self, request: ExecuteTerminalCommand) -> TerminalCommandAccepted | TerminalError: ...
    def write_input(self, request: WriteTerminalInput) -> InputWriteResult | TerminalError: ...
    def stream(self, request: StreamTerminalOutput, sink: TerminalOutputSink) -> StreamResult | TerminalError: ...
    def cancel(self, request: CancelTerminalCommand) -> CancelTerminalResult | TerminalError: ...
    def close(self, request: CloseTerminalSession) -> CloseTerminalResult | TerminalError: ...
    def inspect(self, query: AuthorizedTerminalQuery) -> TerminalSessionSnapshot | TerminalError: ...
    def supervisor(self) -> ProcessSupervisor: ...


class TerminalPort(Protocol):
    def create(self, request: CreateTerminalSession) -> TerminalSessionSnapshot | TerminalError: ...
    def execute(self, request: ExecuteTerminalCommand) -> TerminalCommandAccepted | TerminalError: ...
    def write_input(self, request: WriteTerminalInput) -> InputWriteResult | TerminalError: ...
    def stream(self, request: StreamTerminalOutput, sink: TerminalOutputSink) -> StreamResult | TerminalError: ...
    def inspect(self, query: AuthorizedTerminalQuery) -> TerminalSessionSnapshot | TerminalError: ...
    def request_cancel(self, request: CancelTerminalCommand) -> CancelTerminalResult | TerminalError: ...
    def close(self, request: CloseTerminalSession) -> CloseTerminalResult | TerminalError: ...


__all__ = [name for name in globals() if not name.startswith("_")]
