"""durable worker dispatch and scheduler operation state

Revision ID: 0003_workers_scheduler
Revises: 0002_persistence_integrity
"""
from alembic import op
import sqlalchemy as sa

revision = "0003_workers_scheduler"
down_revision = "0002_persistence_integrity"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("worker_dispatches", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("dispatch_id", sa.String(255), nullable=False, unique=True), sa.Column("execution_id", sa.String(255), nullable=False), sa.Column("user_id", sa.String(255), nullable=False), sa.Column("workspace_id", sa.String(255)), sa.Column("agent_id", sa.String(255), nullable=False), sa.Column("pool", sa.String(32), nullable=False), sa.Column("work_kind", sa.String(64), nullable=False), sa.Column("state", sa.String(32), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("idempotency_key", sa.String(256), nullable=False), sa.Column("payload_ref", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("user_id", "workspace_id", "agent_id", "execution_id", "idempotency_key", name="uq_worker_dispatch_idempotency"), sa.CheckConstraint("version > 0", name="ck_worker_dispatch_version"))
    op.create_index("ix_worker_dispatches_execution_state", "worker_dispatches", ["execution_id", "state"])
    op.create_table("worker_dispatch_attempts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("dispatch_attempt_id", sa.String(255), nullable=False, unique=True), sa.Column("dispatch_id", sa.String(255), nullable=False), sa.Column("attempt_number", sa.Integer(), nullable=False), sa.Column("state", sa.String(32), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("lease_id", sa.String(255)), sa.Column("worker_id", sa.String(255)), sa.Column("fencing_token", sa.Integer()), sa.Column("lease_expires_at", sa.DateTime(timezone=True)), sa.Column("reason_code", sa.String(96)), sa.Column("not_before", sa.DateTime(timezone=True), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["dispatch_id"], ["worker_dispatches.dispatch_id"], name="fk_worker_attempt_dispatch"), sa.UniqueConstraint("dispatch_id", "attempt_number", name="uq_worker_attempt_number"), sa.CheckConstraint("version > 0 AND attempt_number > 0", name="ck_worker_attempt_version"))
    op.create_index("ix_worker_attempts_recovery", "worker_dispatch_attempts", ["state", "lease_expires_at", "expires_at"])
    op.create_table("schedules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("schedule_id", sa.String(255), nullable=False, unique=True), sa.Column("user_id", sa.String(255), nullable=False), sa.Column("workspace_id", sa.String(255)), sa.Column("agent_id", sa.String(255), nullable=False), sa.Column("schedule_type", sa.String(32), nullable=False), sa.Column("target", sa.JSON(), nullable=False), sa.Column("rule", sa.JSON(), nullable=False), sa.Column("timezone", sa.String(128), nullable=False), sa.Column("policies", sa.JSON(), nullable=False), sa.Column("state", sa.String(32), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("next_fire_at", sa.DateTime(timezone=True)), sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False), sa.Column("ends_at", sa.DateTime(timezone=True)), sa.Column("idempotency_key", sa.String(256), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("version > 0", name="ck_schedule_version"))
    op.create_index("ix_schedules_due", "schedules", ["state", "next_fire_at"])
    op.create_table("schedule_occurrences", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("occurrence_id", sa.String(512), nullable=False, unique=True), sa.Column("schedule_id", sa.String(255), nullable=False), sa.Column("schedule_version", sa.Integer(), nullable=False), sa.Column("logical_scheduled_at", sa.DateTime(timezone=True), nullable=False), sa.Column("state", sa.String(32), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("state_fencing_token", sa.Integer(), nullable=False), sa.Column("claim_id", sa.String(512)), sa.Column("claim_owner", sa.String(255)), sa.Column("claim_expires_at", sa.DateTime(timezone=True)), sa.Column("execution_id", sa.String(255)), sa.Column("dispatch_id", sa.String(255)), sa.Column("dispatch_attempt_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("reason_code", sa.String(96)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["schedule_id"], ["schedules.schedule_id"], name="fk_occurrence_schedule"), sa.UniqueConstraint("schedule_id", "schedule_version", "logical_scheduled_at", name="uq_schedule_occurrence_logical"), sa.CheckConstraint("version > 0 AND state_fencing_token >= 0", name="ck_schedule_occurrence_version"))
    op.create_index("ix_schedule_occurrence_recovery", "schedule_occurrences", ["state", "claim_expires_at"])


def downgrade() -> None:
    op.drop_table("schedule_occurrences"); op.drop_table("schedules"); op.drop_table("worker_dispatch_attempts"); op.drop_table("worker_dispatches")
